# Node
resources:
  repositories:
    - repository: TEMPLATES
      type: git
      name: TEMPLATES
      ref: main
      trigger: none

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - template: TEMPLATES/veracode.yml