stages:
- stage: Veracode
  displayName: Veracode
  jobs:
  - job: Veracode
    steps:
    - script: |
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      displayName: 'Download Veracode CLI'

    - task: CmdLine@2
      inputs:
        script: |
          set -e
          WORKDIR="./veracode-artifacts"
          rm -rf "$WORKDIR"
          mkdir -p "$WORKDIR"

          echo "Generating Veracode packages..."
          ./veracode package --source "." --output "$WORKDIR" --verbose

          cd "$WORKDIR"
          ZIP_COUNT=$(find . -maxdepth 1 -name "*.zip" | wc -l)
          echo "ZIPs generated: $ZIP_COUNT"
          if [ "$ZIP_COUNT" -eq 0 ]; then
            echo "No ZIP generated."
            exit 1
          fi

          if [ "$ZIP_COUNT" -eq 1 ]; then
            ZIP_FILE=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
            echo "Only one ZIP found:"
            echo "$ZIP_FILE"
            mv "$ZIP_FILE" veracode-unified.zip

          else
            echo "Merging ZIPs..."
            mkdir merged

            for zip in *.zip; do
              TEMP_DIR=$(mktemp -d)
              echo "Extracting $zip"
              unzip -q "$zip" -d "$TEMP_DIR"
              cp -R "$TEMP_DIR"/. merged/
              rm -rf "$TEMP_DIR"
            done

            cd merged
            zip -r ../veracode-unified.zip .
            cd ..

            echo "Unified ZIP created."
          fi

          echo "Final artifact:"
          ls -lh veracode-unified.zip
      displayName: 'Criando pacote para analise'

    - script: |
        curl -o veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/23.4.11.2/vosp-api-wrappers-java-23.4.11.2.jar
      displayName: 'Download Veracode Wrapper'

    - script: |
        if [ $(Build.SourceBranchName) == 'main' ]; then
            java -jar veracode-wrapper.jar -vid $(VERACODE_API_KEY_ID) -vkey $(VERACODE_API_KEY_SECRET) -action uploadandscan -appname "$(Build.DefinitionName)" -createprofile true  -version $(build.buildNumber) -filepath $(caminhoPacote) -teams "$(veracodeTeams)"
          else
            java -jar veracode-wrapper.jar -vid $(VERACODE_API_KEY_ID) -vkey $(VERACODE_API_KEY_SECRET) -action uploadandscan -appname "$(Build.DefinitionName)" -createprofile true  -version $(build.buildNumber) -filepath $(caminhoPacote) -teams "$(veracodeTeams)" -createsandbox true -sandboxname "$(Build.SourceBranchName)"
          fi
      displayName: 'Veracode U&S'
      continueOnError: true

    - script: |
          curl -sSL https://download.srcclr.com/ci.sh | bash  scan --update-advisor --allow-dirty
      displayName: 'Veracode SCA'
      continueOnError: true

    - script: |
        ./veracode scan --type directory --source ./ --format table
      displayName: 'Veracode IaC'

    - script: |
          ./veracode static scan "$(caminhoPacote)" 
      displayName: 'Veracode SAST'
      continueOnError: true